### ISSUE TITLE
Single request per page

### ISSUE THREAD

**Issue by miku** [golang-leipzig/golang-leipzig.github.io#7]
Just read: https://getkiss.org/blog/20191004a

It's just beautiful and superfast - if anyone would be up for a challenge to figure out how to do something like this with hugo, I'd be +1 on this. Apart from that, it might be just a waste of time - most pages - we do at not much more than 3 requests per page currently, which is already fine.

**Comment by klingtnet** [comment]
I also read this article and think that it was a nice achievement having a website with all resources that is loaded in a single request.
But, this would break browser caching our case, since the only things we load besides the website is the favicon and our SVG logo. Hence, it would make our website slower and that is why I'm against this change.

**Comment by miku** [comment]
True. I was caught by the minimalism.

Not sure, if inlining the favicon would make sense either, out homepage html is about 5kb, the favicon about 15kb.
